geocity/apps/accounts/urls.py
import logging

from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

logger = logging.getLogger(__name__)

app_name = "accounts"

urlpatterns = []

if settings.ENABLE_2FA:
    from two_factor.views import SetupCompleteView

    logger.info("2 factors authentification is enabled")
    urlpatterns += [
        path(
            "account/login/",
            views.CustomLoginView.as_view(template_name="two_factor/login.html"),
            name="account_login",
        ),
        path(
            "account/two_factor/",
            views.Custom2FAProfileView.as_view(template_name="two_factor/profile.html"),
            name="profile",
        ),
        path(
            "account/two_factor/setup/complete/",
            SetupCompleteView.as_view(template_name="two_factor/setup_complete.html"),
            name="setup_complete",
        ),
    ]
else:
    logger.info("2 factors authentification is disabled")
    urlpatterns += [
        path(
            "account/login/",
            views.CustomLoginView.as_view(template_name="registration/login.html"),
            name="account_login",
        ),
    ]

urlpatterns += [
    path(
        "account/logout/",
        views.logout_view,
        name="logout",
    ),
    path(
        "account/lockout/",
        views.lockout_view,
        name="lockout",
    ),
    path(
        "account/password_reset/done",
        auth_views.PasswordResetDoneView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "account/password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "account/activate/<uid>/<token>/",
        views.ActivateAccountView.as_view(),
        name="activate_account",
    ),
    path("profile/create/", views.user_profile_create, name="user_profile_create"),
    path("profile/edit/", views.user_profile_edit, name="user_profile_edit"),
    path(
        "admin-data/<path:path>",
        views.administrative_entity_file_download,
        name="administrative_entity_file_download",
    ),
]

geocity/apps/submissions/urls.py
from django.urls import include, path

from . import views

app_name = "submissions"

submission_urlpatterns = [
    path(
        "administrative-entity/",
        views.submission_select_administrative_entity,
        name="submission_select_administrative_entity",
    ),
]

anonymous_submission_urlpatterns = [
    path(
        "anonymous/",
        views.anonymous_submission,
        name="anonymous_submission",
    ),
    path(
        "anonymous/sent",
        views.anonymous_submission_sent,
        name="anonymous_submission_sent",
    ),
]

existing_submission_urlpatterns = [
    path("", views.SubmissionDetailView.as_view(), name="submission_detail"),
    path(
        "objects/",
        views.submission_select_forms,
        name="submission_select_forms",
    ),
    path("properties/", views.submission_fields, name="submission_fields"),
    path("appendices/", views.submission_appendices, name="submission_appendices"),
    path("actors/", views.submission_contacts, name="submission_contacts"),
    path("submit/", views.submission_submit, name="submission_submit"),
    path(
        "submitconfirmed/",
        views.submission_submit_confirmed,
        name="submission_submit_confirmed",
    ),
    path("geotime/", views.submission_geo_time, name="submission_geo_time"),
    path("delete/", views.submission_delete, name="submission_delete"),
    path("approve/", views.submission_approve, name="submission_approve"),
    path("reject/", views.submission_reject, name="submission_reject"),
    path(
        "prolongation/",
        views.submission_prolongation,
        name="submission_prolongation",
    ),
]

urlpatterns = [
    path(
        "<int:submission_id>/",
        include(submission_urlpatterns + existing_submission_urlpatterns),
    ),
    # TODO: adapt path name here and in front app
    path(
        "permits-files/<path:path>",
        views.submission_file_download,
        name="submission_file_download",
    ),
    path(
        "form-files/<path:path>",
        views.field_file_download,
        name="field_file_download",
    ),
    path(
        "documents/<path:path>/download",
        views.ComplementaryDocumentDownloadView.as_view(),
        name="complementary_documents_download",
    ),
    path(
        "documents/<int:pk>/delete",
        views.submission_complementary_document_delete,
        name="complementary_documents_delete",
    ),
    path("", views.SubmissionList.as_view(), name="submissions_list"),
    path("", include(submission_urlpatterns + anonymous_submission_urlpatterns)),
    path(
        "media/<int:property_value_id>/",
        views.submission_media_download,
        name="submission_media_download",
    ),
    path(
        "adminentitiesgeojson/<int:administrative_entity_id>/",
        views.administrative_entities_geojson,
        name="administrative_entities_geojson",
    ),
    path("search/", views.submissions_search, name="submissions_search"),
    path(
        "archives/",
        views.ArchivedSubmissionListView.as_view(),
        name="archived_submission_list",
    ),
    path(
        "archives/<int:pk>/delete",
        views.ArchivedSubmissionDeleteView.as_view(),
        name="archived_submission_delete",
    ),
    path(
        "archives/<int:pk>/download",
        views.ArchivedSubmissionDownloadView.as_view(),
        name="archived_submission_download",
    ),
    path(
        "archives/bulk-download",
        views.ArchivedSubmissionBulkDownloadView.as_view(),
        name="archived_submission_bulk_download",
    ),
    path(
        "transactions/<str:merchant_reference>/change-status",
        views.ChangeTransactionStatus.as_view(),
        name="change_transaction_status",
    ),
    path(
        "transactions/confirm/<int:pk>",
        views.ConfirmTransactionCallback.as_view(),
        name="confirm_transaction",
    ),
    path(
        "transactions/fail/<int:pk>",
        views.FailTransactionCallback.as_view(),
        name="fail_transaction",
    ),
    path(
        "payment/<int:pk>",
        views.SubmissionPaymentRedirect.as_view(),
        name="submission_payment_redirect",
    ),
    path(
        "validations/<int:submission_id>/edit",
        views.submission_validations_edit,
        name="submission_validations_edit",
    ),
]

geocity/urls.py
import logging

from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path

import geocity.apps.api.urls
from geocity.apps.accounts.dootix.provider import DootixProvider
from geocity.apps.accounts.geomapfish.provider import GeomapfishProvider
from geocity.apps.django_wfs3.urls import wfs3_router
from geocity.apps.submissions import views as submissions_views

from .views import legacy_urls_redirect

logger = logging.getLogger(__name__)

# See TWO_FACTOR_PATCH_ADMIN
if settings.ENABLE_2FA:
    from .admin_site_2fa import AdminSiteOTPRequiredMixinRedirSetup

    admin.site = AdminSiteOTPRequiredMixinRedirSetup()


# Django-configuration
urlpatterns = (
    [
        path("", submissions_views.submission_select_administrative_entity),
        path("submissions/", include("geocity.apps.submissions.urls")),
        path("forms/", include("geocity.apps.forms.urls")),
        path("reports/", include("geocity.apps.reports.urls")),
        # Backward compatibility for Geocity < 2.1, will be deprecated in 3.0
        re_path(r"permit-requests/.*", legacy_urls_redirect),
    ]
    + default_urlpatterns(GeomapfishProvider)
    + default_urlpatterns(DootixProvider)
)


urlpatterns += [
    path("", include("geocity.apps.accounts.urls")),
    path("rest/", include(geocity.apps.api.urls)),  # Django-rest urls
    path("wfs3/", include(wfs3_router.urls)),  # Django-rest urls
    path("captcha/", include("captcha.urls")),
    path("api-tokens/", include("knox.urls")),
    path("account/", include("django.contrib.auth.urls")),
    path("oauth/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    path("admin/", admin.site.urls),
    path("accounts/social/", include("allauth.socialaccount.urls")),
]

if settings.ENABLE_2FA:
    from two_factor.urls import urlpatterns as tf_urls

    urlpatterns += [
        path("", include(tf_urls)),
    ]

if settings.PREFIX_URL:
    urlpatterns = [path(settings.PREFIX_URL, include(urlpatterns))]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

geocity/apps/core/templates/base_generic.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="referrer" content="strict-origin-when-cross-origin">
    <title>{% block title %}{% endblock %}Geocity</title>
    {% load static %}
    {% load i18n %}
    {% load bootstrap4 %}
    {% load submissions_extras %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% block script %}
      <script src="https://use.fontawesome.com/006d51a83c.js"></script>
      <script
        type="text/javascript"
        src="{% static "django_tables2_column_shifter/js/django_tables2_column_shifter.min.js" %}">
      </script>
      <script src="{% static "js/search.js" %}"></script>
    {% endblock %}
    {% block stylesheets %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% endblock %}
    <link rel="icon" href="{% static 'images/favicon.ico'%}" type="image/svg" sizes="16x16">
    <style>
      :root {
      --background-color: {{ config.BACKGROUND_COLOR }};
      --primary-color: {{ config.PRIMARY_COLOR }};
      --secondary-color: {{ config.SECONDARY_COLOR }};
      --text-color: {{ config.TEXT_COLOR }};
      --title-color: {{ config.TITLE_COLOR }};
      --table-color: {{ config.TABLE_COLOR }};
      --login-background-color:{{ config.LOGIN_BACKGROUND_COLOR }};
      }
    </style>
  </head>

  <body class="d-flex flex-column min-vh-100">

    <header class="header_navigation" id="banner">
      <!-- Navbar -->
      {% block navbar %}
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 sticky-top">
          <div class="navbar-brand d-flex align-items-center">
              <img src={% static "images/geocity_normal.svg" %} style="vertical-align:baseline" alt="logo" height="16"/>
          </div>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-toggle" aria-controls="navbar-toggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          {% if user.is_authenticated and not user.userprofile.is_temporary %}
            <div class="collapse navbar-collapse navbar-toggle">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item d-flex align-items-center">
                    <a href="{% url 'submissions:submissions_list' %}" role="button">
                      <i class="fa fa-list-ul" aria-hidden="true"></i>
                      {% translate "Mes demandes" %}
                    </a>
                </li>
                {% can_archive as can_archive %}
                {% if can_archive %}
                  <li class="nav-item d-flex align-items-center">
                      <a href="{% url 'submissions:archived_submission_list' %}" role="button">
                        <i class="fa fa-archive" aria-hidden="true"></i>
                        {% translate "Demandes archivées" %}
                      </a>
                  </li>
                {% endif %}
                  {% if config.ENABLE_GEOCALENDAR %}
                    <li class="nav-item d-flex align-items-center">
                      <a href="{{ config.GEOCALENDAR_URL }}" target="_blank" rel="noreferrer" role="button">
                        <i class="fa fa-calendar aria-hidden="true"></i>
                        {% translate "Calendrier" %}
                      </a>
                    </li>
                  {% endif %}

                  {% if group.permit_department.administrative_entity.archive_link %}
                <li class="nav-item d-flex align-items-center">
                  {% with request.user.groups.all|first as group %}
                    {% if group.permit_department.administrative_entity.archive_link != '' %}
                      {% if request.user.groups.all.count > 0 %}
                        <a class="btn btn-outline-primary" href="{{group.permit_department.administrative_entity.archive_link}}" role="button" target="_blank" rel="noreferrer">
                          <i class="fa fa-archive"></i>
                          {% translate "Archives" %}</a>
                      {% endif %}
                    {% endif %}
                  {% endwith %}

                {% endif %}
              </ul>
              <ul class="navbar-nav ml-auto">
                <li class="nav-item d-flex align-items-center">
                  <div class="global-search-form-container">
                    <form  class="navbar-form navbar-right" method="get" action="{% url 'submissions:submissions_search' %}" id="global-search-form">
                      <input data-role="search-input" placeholder="{% translate "Recherche…" %}" type="text" name="search" class="w-100 search-input form-control" autocomplete="off">
                      <div data-role="search-results" class="search-results-container"></div>
                    </form>
                  </div>
                </li>
                <li class="nav-item d-flex align-items-center" title="{% translate 'Imprimer cette page' %}">
                  <a href="javascript:window.print()" class="text-secondary" role="button">
                    <i class="fa fa-print" aria-hidden="true"></i>&nbsp;{% translate "Imprimer" %}
                  </a>
                </li>
                <li class="nav-item d-flex align-items-center login-navbar-desktop">
                    <a class="nav-link dropdown-toggle ml-auto" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fa fa-user"></i>
                      {% block connected_user %}<b>{{ user.get_username }}</b>{% endblock %}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                      {% if user.is_staff %}
                      <a class="dropdown-item" href="{% url 'admin:index' %}">{% translate "Interface d'administration" %}</a>
                      <div class="dropdown-divider"></div>
                      {% endif %}
                      <a class="dropdown-item" href="{% url 'accounts:user_profile_edit' %}">{% translate "Gérer mon compte" %}</a>
                      {% if ENABLE_2FA %}
                      <a class="dropdown-item" href="{% url 'two_factor:profile' %}">{% translate "Gérer la sécurité de mon compte" %}</a>
                      {% endif %}
                      {% if not user.socialaccount_set.exists %}
                      <a class="dropdown-item" href="{% url 'accounts:password_change' %}">{% translate "Modifier mon mot de passe" %}</a>
                      {% endif %}
                      <div class="dropdown-divider"></div>
                      <form method="post" action="{% url 'accounts:logout' %}">
                        {% csrf_token %}
                        <button class="btn dropdown-item">
                          {% translate "Me déconnecter" %}
                        </button>
                      </form>
                  </div>
                </li>
                <li class="nav-item d-flex align-items-center login-navbar-mobile">
                   <!-- On mobile -->
                  <div class="collapse navbar-collapse navbar-toggle" id="navbarNavDropdown">
                    <ul class="navbar-nav d-flex d-md-none">
                      {% if user.is_staff %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">{% translate "Interface d'administration" %}</a>
                      </li>
                      <div class="dropdown-divider"></div>
                      {% endif %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:user_profile_edit' %}">{% translate "Gérer mon compte" %}</a>
                      </li>
                      {% if ENABLE_2FA %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'two_factor:profile' %}">{% translate "Gérer la sécurité de mon compte" %}</a>
                      </li>
                      {% endif %}
                      {% if not user.socialaccount_set.exists %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:password_change' %}">{% translate "Modifier mon mot de passe" %}</a>
                      </li>
                      {% endif %}
                      <div class="dropdown-divider"></div>
                      <li class="nav-item">
                        <form method="post" action="{% url 'accounts:logout' %}">
                          {% csrf_token %}
                          <button class="btn btn-block text-left nav-link">
                            {% translate "Me déconnecter" %}
                          </button>
                        </form>
                      </li>
                    </ul>
                  </div>
                </li>

              </ul>
            </div>
          {% endif %}

        </nav>

      {% endblock %}
    </header>

      {% if messages %}
        <div class="container-fluid mb-4">
          {% for message in messages %}
            <div class="alert
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
              alert-danger
              {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
              alert-success
              {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
              alert-warning
              {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
              alert-info
              {% endif %}
              ">{{ message }}</div>
          {% endfor %}
        </div>
      {% endif %}

      <div class="container mb-0 px-3 px-md-0">
        {% block content %}{% endblock %}
      </div>

      <div class="container-fluid">
        {% block content-fluid %}{% endblock %}
      </div>

      <footer class="flex-shrink-0 py-2 bg-light text-dark mt-auto">
        <div class="container text-center">
          <small>
            &copy; {% now "Y" %} Geocity
            &nbsp;|&nbsp;
            <a href="https://geocity.ch/about" target="_blank" rel="noreferrer">{% translate "A propos" %}</a>
            {% if config.CONTACT_URL %}
              &nbsp;|&nbsp;
              <a href="{{ config.CONTACT_URL }}" target="_blank" rel="noreferrer">{% translate "Contact" %}</a>
            {% endif %}
            {% if config.GENERAL_CONDITIONS_URL %}
              &nbsp;|&nbsp;
              <a href="{{ config.GENERAL_CONDITIONS_URL }}" target="_blank" rel="noreferrer">{% translate "Conditions" %}</a>
            {% endif %}
            {% if config.PRIVACY_POLICY_URL %}
              &nbsp;|&nbsp;
              <a href="{{ config.PRIVACY_POLICY_URL }}" target="_blank" rel="noreferrer">{% translate "Confidentialité" %}</a>
            {% endif %}
          </small>
        </div>
      </footer>

      {% block scripts %}{% endblock %}


  </body>
</html>